baseURL = 'http://lucas-ricci.com/'
title = 'Lucas Ricci'

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 10

    [[menu.main]]
        name = "Projetos"
        url = "/projetos"
        weight = 20

    [[menu.main]]
        name = "Contato"
        URL = "/contato"
        weight = 30

    [[menu.main]]
        name = "Livro"
        url = "/livros"
        weight = 40
        
    [[menu.social]]
        name = "Github"
        url = "https://github.com/lucasricci"
        weight = 50


